//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteCoreWebSite.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.SiteCoreWebServiceSoap")]
    public interface SiteCoreWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        SiteCoreWebSite.WebService.LoginResponse Login(SiteCoreWebSite.WebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<SiteCoreWebSite.WebService.LoginResponse> LoginAsync(SiteCoreWebSite.WebService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        SiteCoreWebSite.WebService.RegisterResponse Register(SiteCoreWebSite.WebService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<SiteCoreWebSite.WebService.RegisterResponse> RegisterAsync(SiteCoreWebSite.WebService.RegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public SiteCoreWebSite.WebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(SiteCoreWebSite.WebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string key;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password, string loginDate, string key) {
            this.username = username;
            this.password = password;
            this.loginDate = loginDate;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SiteCoreWebSite.WebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(SiteCoreWebSite.WebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public SiteCoreWebSite.WebService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(SiteCoreWebSite.WebService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string key;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string username, string password, string loginDate, string key) {
            this.username = username;
            this.password = password;
            this.loginDate = loginDate;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public SiteCoreWebSite.WebService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(SiteCoreWebSite.WebService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(bool RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteCoreWebServiceSoapChannel : SiteCoreWebSite.WebService.SiteCoreWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteCoreWebServiceSoapClient : System.ServiceModel.ClientBase<SiteCoreWebSite.WebService.SiteCoreWebServiceSoap>, SiteCoreWebSite.WebService.SiteCoreWebServiceSoap {
        
        public SiteCoreWebServiceSoapClient() {
        }
        
        public SiteCoreWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteCoreWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteCoreWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteCoreWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiteCoreWebSite.WebService.LoginResponse SiteCoreWebSite.WebService.SiteCoreWebServiceSoap.Login(SiteCoreWebSite.WebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string username, string password, string loginDate, string key) {
            SiteCoreWebSite.WebService.LoginRequest inValue = new SiteCoreWebSite.WebService.LoginRequest();
            inValue.Body = new SiteCoreWebSite.WebService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.loginDate = loginDate;
            inValue.Body.key = key;
            SiteCoreWebSite.WebService.LoginResponse retVal = ((SiteCoreWebSite.WebService.SiteCoreWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiteCoreWebSite.WebService.LoginResponse> SiteCoreWebSite.WebService.SiteCoreWebServiceSoap.LoginAsync(SiteCoreWebSite.WebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiteCoreWebSite.WebService.LoginResponse> LoginAsync(string username, string password, string loginDate, string key) {
            SiteCoreWebSite.WebService.LoginRequest inValue = new SiteCoreWebSite.WebService.LoginRequest();
            inValue.Body = new SiteCoreWebSite.WebService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.loginDate = loginDate;
            inValue.Body.key = key;
            return ((SiteCoreWebSite.WebService.SiteCoreWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiteCoreWebSite.WebService.RegisterResponse SiteCoreWebSite.WebService.SiteCoreWebServiceSoap.Register(SiteCoreWebSite.WebService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public bool Register(string username, string password, string loginDate, string key) {
            SiteCoreWebSite.WebService.RegisterRequest inValue = new SiteCoreWebSite.WebService.RegisterRequest();
            inValue.Body = new SiteCoreWebSite.WebService.RegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.loginDate = loginDate;
            inValue.Body.key = key;
            SiteCoreWebSite.WebService.RegisterResponse retVal = ((SiteCoreWebSite.WebService.SiteCoreWebServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiteCoreWebSite.WebService.RegisterResponse> SiteCoreWebSite.WebService.SiteCoreWebServiceSoap.RegisterAsync(SiteCoreWebSite.WebService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiteCoreWebSite.WebService.RegisterResponse> RegisterAsync(string username, string password, string loginDate, string key) {
            SiteCoreWebSite.WebService.RegisterRequest inValue = new SiteCoreWebSite.WebService.RegisterRequest();
            inValue.Body = new SiteCoreWebSite.WebService.RegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.loginDate = loginDate;
            inValue.Body.key = key;
            return ((SiteCoreWebSite.WebService.SiteCoreWebServiceSoap)(this)).RegisterAsync(inValue);
        }
    }
}
